services:
  # Mod Evaluator Backend
  mod-evaluator:
    build: ./mod-evaluator/backend
    container_name: swgoh_mod_evaluator
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./shared-data:/app/shared-data:ro
    environment:
      - PYTHONPATH=/app
      - LOG_LEVEL=INFO
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  default:
    name: swgoh-network